-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Sep 30, 2022 at 12:32 AM
-- Server version: 5.7.36
-- PHP Version: 7.4.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `moviedb`
--

-- --------------------------------------------------------

--
-- Table structure for table `movie`
--

DROP TABLE IF EXISTS `movie`;
CREATE TABLE IF NOT EXISTS `movie` (
  `id` int(11) NOT NULL,
  `movie_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `original_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `release_date` date NOT NULL,
  `image` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image_link` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `overview` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `genres` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `movie`
--

INSERT INTO `movie` (`id`, `movie_name`, `original_name`, `release_date`, `image`, `image_link`, `overview`, `genres`, `category`) VALUES
(19995, 'Avatar', 'Avatar', '2009-12-10', '/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg', 'https://image.tmdb.org/t/p/original/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg', 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.', 'Action, Adventure, Fantasy, Science Fiction', 'Now Playing,Popular'),
(438148, 'Minions: The Rise of Gru', 'Minions: The Rise of Gru', '2022-06-29', '/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg', 'https://image.tmdb.org/t/p/original/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg', 'A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.', 'Animation, Adventure, Comedy, Fantasy', 'Now Playing,Popular'),
(539681, 'DC League of Super-Pets', 'DC League of Super-Pets', '2022-07-27', '/r7XifzvtezNt31ypvsmb6Oqxw49.jpg', 'https://image.tmdb.org/t/p/original/r7XifzvtezNt31ypvsmb6Oqxw49.jpg', 'When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.', 'Animation, Action, Adventure', 'Now Playing,Popular'),
(610150, 'Dragon Ball Super: Super Hero', 'ドラゴンボール超 スーパーヒーロー', '2022-06-11', '/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg', 'https://image.tmdb.org/t/p/original/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg', 'The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.', 'Animation, Science Fiction, Action', 'Now Playing,Popular,Upcoming'),
(619730, 'Don\'t Worry Darling', 'Don\'t Worry Darling', '2022-09-21', '/rwev45KqwP0c0E0cfVEsRSubxQu.jpg', 'https://image.tmdb.org/t/p/original/rwev45KqwP0c0E0cfVEsRSubxQu.jpg', 'Alice and Jack are lucky to be living in the idealized community of Victory, the experimental company town housing the men who work for the top-secret Victory Project and their families. But when cracks in their idyllic life begin to appear, exposing flashes of something much more sinister lurking beneath the attractive façade, Alice can’t help questioning exactly what they’re doing in Victory, and why.', 'Drama, Mystery, Thriller, Science Fiction', 'Now Playing,Upcoming'),
(634649, 'Spider-Man: No Way Home', 'Spider-Man: No Way Home', '2021-12-15', '/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg', 'https://image.tmdb.org/t/p/original/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg', 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.', 'Action, Adventure, Science Fiction', 'Now Playing,Popular,Upcoming'),
(576925, 'My Sweet Monster', 'Buka. My favorite monster', '2022-01-27', '/xIbEHAqwK5N7PJJYmbwmxuvC7fL.jpg', 'https://image.tmdb.org/t/p/original/xIbEHAqwK5N7PJJYmbwmxuvC7fL.jpg', 'A scandal in the royal family: the wayward princess Barbara escaped from the palace and went through the forest in search of a handsome prince. However, instead of the cherished meeting with her beloved, she is captured by Buka, the most dangerous robber of the kingdom. But it quickly becomes clear that the brisk princess is ready to turn Buka\'s life into a nightmare, just to reach her goal. So the restless Varvara begins to establish her own order in the forest.', 'Animation, Adventure, Family', 'Now Playing'),
(877957, 'Drifting Home', '雨を告げる漂流団地', '2022-09-09', '/iNf1wC8cK6e8zgNyuMUqWFT7Din.jpg', 'https://image.tmdb.org/t/p/original/iNf1wC8cK6e8zgNyuMUqWFT7Din.jpg', 'Sixth-graders Kosuke and Natsume grew up in the same apartment building as childhood friends. During summer break, while playing in the apartment building that is set to be demolished, they find themselves caught in a strange phenomenon. All they can see around them is a vast sea. Will Kosuke and the others make it back to their world? A journey of farewells in summer has just begun.', 'Animation, Drama, Mystery, Fantasy, Family', 'Now Playing'),
(999205, 'Stowaway', 'Stowaway', '2022-08-31', '/1RmugOkBFU5eXu1dbr1zdxChLfQ.jpg', 'https://image.tmdb.org/t/p/original/1RmugOkBFU5eXu1dbr1zdxChLfQ.jpg', 'A tenacious party girl fights to survive after three thieves commandeer her luxury yacht. Unable to escape and trapped on the yacht at high seas, the prey becomes the hunter as she turns the tables on the intruders and takes matters into her own hands.', 'Thriller, Action', 'Now Playing'),
(639933, 'The Northman', 'The Northman', '2022-04-07', '/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg', 'https://image.tmdb.org/t/p/original/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg', 'Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy\'s mother. Two decades later, Amleth is now a Viking who\'s on a mission to save his mother, kill his uncle and avenge his father.', 'Action, Adventure, Fantasy', 'Now Playing'),
(852448, 'I Came By', 'I Came By', '2022-08-19', '/856bLLUvEYu3dRDXCCoRE7oxO0V.jpg', 'https://image.tmdb.org/t/p/original/856bLLUvEYu3dRDXCCoRE7oxO0V.jpg', 'A rebellious young graffiti artist, who targets the homes of the wealthy elite, discovers a shocking secret that leads him on a journey endangering himself and those closest to him.', 'Thriller', 'Now Playing'),
(526896, 'Morbius', 'Morbius', '2022-03-30', '/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg', 'https://image.tmdb.org/t/p/original/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg', 'Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.', 'Action, Science Fiction, Fantasy', 'Now Playing'),
(961484, 'Last Seen Alive', 'Last Seen Alive', '2022-05-19', '/fJByebN5zDnjE4QHlXC08iOYHlp.jpg', 'https://image.tmdb.org/t/p/original/fJByebN5zDnjE4QHlXC08iOYHlp.jpg', 'After Will Spann\'s wife suddenly vanishes at a gas station, his desperate search to find her leads him down a dark path that forces him to run from authorities and take the law into his own hands.', 'Action, Thriller', 'Now Playing'),
(717728, 'Jeepers Creepers: Reborn', 'Jeepers Creepers: Reborn', '2022-09-15', '/pyFyhcXx4kNnLbzEY5z5fc3RehQ.jpg', 'https://image.tmdb.org/t/p/original/pyFyhcXx4kNnLbzEY5z5fc3RehQ.jpg', 'Forced to travel with her boyfriend to a horror festival, Laine begins to experience disturbing visions associated with the urban legend of The Creeper. As the festival arrives and the blood-soaked entertainment builds to a frenzy, she becomes the center of it while something unearthly has been summoned.', 'Horror, Thriller, Mystery', 'Now Playing'),
(851303, 'Waiting for Bojangles', 'En attendant Bojangles', '2022-01-05', '/x7pOnu6IfkTFkkOguXPKK81ME4g.jpg', 'https://image.tmdb.org/t/p/original/x7pOnu6IfkTFkkOguXPKK81ME4g.jpg', 'In front of their little boy, Camille and Georges dance on their favorite song \"Mr Bojangles\". With them, there is only place for fun and fantasy. The one who shows the way is the mother, an unpredictable wisp. She leads them into a whirlwind of poetry so that the party continues again and again, no matter what happens. Mad love has never lived up to its name so well.', 'Drama, Romance, Comedy', 'Now Playing'),
(675353, 'Sonic the Hedgehog 2', 'Sonic the Hedgehog 2', '2022-03-30', '/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg', 'https://image.tmdb.org/t/p/original/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg', 'After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.', 'Action, Adventure, Family, Comedy', 'Now Playing,Popular'),
(682507, 'Where the Crawdads Sing', 'Where the Crawdads Sing', '2022-07-15', '/6h5OCqRnWH7Dcm4IeP4JypBdtuI.jpg', 'https://image.tmdb.org/t/p/original/6h5OCqRnWH7Dcm4IeP4JypBdtuI.jpg', 'Abandoned by her family, Kya raises herself all alone in the marshes outside of her small town. When her former boyfriend is found dead, Kya is instantly branded by the local townspeople and law enforcement as the prime suspect for his murder.', 'Drama, Mystery, Thriller', 'Now Playing,Upcoming'),
(854467, 'Indemnity', 'Indemnity', '2022-02-11', '/tVbO8EAbegVtVkrl8wNhzoxS84N.jpg', 'https://image.tmdb.org/t/p/original/tVbO8EAbegVtVkrl8wNhzoxS84N.jpg', 'An ex-fireman with PTSD goes on the run when accused of a crime he doesn\'t even remember committing, leading him down a rabbit hole of conspiracy to the highest degree.', 'Action, Thriller, Crime', 'Now Playing'),
(960258, 'Shark Bait', 'Shark Bait', '2022-05-13', '/bVUgMgVozyFScDM3quP412kXrT.jpg', 'https://image.tmdb.org/t/p/original/bVUgMgVozyFScDM3quP412kXrT.jpg', 'A group of friends enjoying a weekend steal a couple of jetskis racing them out to sea, ending up in a horrific head-on collision. They struggle to find a way home with a badly injured friend while from the waters below predators lurk.', 'Horror, Thriller, Action, Adventure', 'Now Playing'),
(811596, 'Notre-Dame on Fire', 'Notre-Dame brûle', '2022-03-16', '/kXj3FqzQABWsElUuT9y3WhfGPdT.jpg', 'https://image.tmdb.org/t/p/original/kXj3FqzQABWsElUuT9y3WhfGPdT.jpg', 'A film relating from the inside the Notre-Dame de Paris fire of April 2019.', 'Drama, Thriller', 'Now Playing'),
(1018552, 'Las Vocales', 'Las Vocales', '2022-08-31', '/zTPL2U9glusiPwOBFoO3IeBiKDK.jpg', 'https://image.tmdb.org/t/p/original/zTPL2U9glusiPwOBFoO3IeBiKDK.jpg', '', 'Comedy', 'Now Playing'),
(601796, 'Alienoid', '외계+인 1부', '2022-07-20', '/qHXTUUJ3Rsxw67Ns75u6RdGNaMJ.jpg', 'https://image.tmdb.org/t/p/original/qHXTUUJ3Rsxw67Ns75u6RdGNaMJ.jpg', 'Gurus in the late Goryeo dynasty try to obtain a fabled, holy sword, and humans in 2022 hunt down an alien prisoner that is locked in a human\'s body. The two parties cross paths when a time-traveling portal opens up.', 'Action, Fantasy, Mystery, Science Fiction, Comedy, Adventure', 'Now Playing'),
(999127, 'Broad Peak', 'Broad Peak', '2022-09-09', '/trbZSMZHzRf7uAPieWwvQ81J0dr.jpg', 'https://image.tmdb.org/t/p/original/trbZSMZHzRf7uAPieWwvQ81J0dr.jpg', 'After climbing Broad Peak mountain, Maciej Berbeka learns his journey to the summit is incomplete. 25 years later, he sets out to finish what he started.', 'Drama', 'Now Playing'),
(697799, 'WarHunt', 'WarHunt', '2022-01-21', '/9HFFwZOTBB7IPFmn9E0MXdWave3.jpg', 'https://image.tmdb.org/t/p/original/9HFFwZOTBB7IPFmn9E0MXdWave3.jpg', '1945. A U.S. military cargo plane loses control and violently crashes behind enemy lines in the middle of the German black forest. Major Johnson sends a squad of his bravest soldiers on a rescue mission to retrieve the top-secret material the plane was carrying, led by Sergeants Brewer and Walsh. They soon discover hanged Nazi soldiers and other dead bodies bearing ancient, magical symbols. Suddenly their compasses fail, their perceptions twist and straying from the group leads to profound horrors as they are attacked by a powerful, supernatural force.', 'Action, Horror, Thriller, War, Fantasy', 'Now Playing'),
(1013228, 'I Used to Be Famous', 'I Used to Be Famous', '2022-09-09', '/hJMnsf6vzgoNx0bv3uh3PTCjmks.jpg', 'https://image.tmdb.org/t/p/original/hJMnsf6vzgoNx0bv3uh3PTCjmks.jpg', 'A former boy band star unexpectedly gets a second shot at success when he forms a bond with a gifted young drummer.', 'Comedy, Drama, Music', 'Now Playing'),
(705996, 'Decision to Leave', '헤어질 결심', '2022-06-29', '/vvdEFKmp9q5F4V3PhCj9FWUFPC2.jpg', 'https://image.tmdb.org/t/p/original/vvdEFKmp9q5F4V3PhCj9FWUFPC2.jpg', 'From a mountain peak in South Korea, a man plummets to his death. Did he jump, or was he pushed? When detective Hae-joon arrives on the scene, he begins to suspect the dead man’s wife Seo-rae. But as he digs deeper into the investigation, he finds himself trapped in a web of deception and desire.', 'Crime, Drama, Romance, Mystery', 'Now Playing,Upcoming'),
(823625, 'Blacklight', 'Blacklight', '2022-02-10', '/bv9dy8mnwftdY2j6gG39gCfSFpV.jpg', 'https://image.tmdb.org/t/p/original/bv9dy8mnwftdY2j6gG39gCfSFpV.jpg', 'Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.', 'Action, Thriller', 'Now Playing'),
(619803, 'The Roundup', '범죄도시 2', '2022-05-18', '/tqHXCshqysM6DPnXeFIR74fNdKw.jpg', 'https://image.tmdb.org/t/p/original/tqHXCshqysM6DPnXeFIR74fNdKw.jpg', 'The ‘Beast Cop’ Ma Seok-do heads to a foreign country to extradite a suspect, but soon after his arrival, he discovers additional murder cases and hears about a vicious killer who has been committing crimes against tourists for several years.', 'Crime, Action', 'Now Playing'),
(916605, 'The Infernal Machine', 'The Infernal Machine', '2022-09-23', '/bSqpOGzaKBdGkBLmcm1JJIVryYy.jpg', 'https://image.tmdb.org/t/p/original/bSqpOGzaKBdGkBLmcm1JJIVryYy.jpg', 'Reclusive and controversial author Bruce Cogburn is drawn out of hiding by an obsessive fan, forcing the novelist to confront a past that he thought he could escape, and to account for events set in motion by his bestseller decades earlier. Cogburn\'s search for who is behind the manipulation and mental torment he encounters leads to an emotional roller-coaster ride full of fear and danger, where things are not always as clear as they seem to be, and where past deeds can have dire consequences.', 'Thriller', 'Now Playing'),
(718930, 'Bullet Train', 'Bullet Train', '2022-07-03', '/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg', 'https://image.tmdb.org/t/p/original/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg', 'Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug\'s latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world\'s fastest train.', 'Action, Comedy, Thriller', 'Now Playing,Popular'),
(532639, 'Pinocchio', 'Pinocchio', '2022-09-07', '/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg', 'https://image.tmdb.org/t/p/original/g8sclIV4gj1TZqUpnL82hKOTK3B.jpg', 'A wooden puppet embarks on a thrilling adventure to become a real boy.', 'Fantasy, Adventure, Family', 'Popular'),
(744276, 'After Ever Happy', 'After Ever Happy', '2022-08-24', '/6b7swg6DLqXCO3XUsMnv6RwDMW2.jpg', 'https://image.tmdb.org/t/p/original/6b7swg6DLqXCO3XUsMnv6RwDMW2.jpg', 'As a shocking truth about a couple\'s families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.', 'Romance, Drama', 'Now Playing,Popular'),
(629176, 'Samaritan', 'Samaritan', '2022-08-25', '/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg', 'https://image.tmdb.org/t/p/original/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg', 'Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.', 'Action, Drama, Science Fiction', 'Popular'),
(579974, 'RRR', 'రౌద్రం రణం రుధిరం', '2022-03-24', '/wE0I6efAW4cDDmZQWtwZMOW44EJ.jpg', 'https://image.tmdb.org/t/p/original/wE0I6efAW4cDDmZQWtwZMOW44EJ.jpg', 'A fictional history of two legendary revolutionaries\' journey away from home before they began fighting for their country in the 1920s.', 'Action, Drama', 'Popular'),
(616037, 'Thor: Love and Thunder', 'Thor: Love and Thunder', '2022-07-06', '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg', 'https://image.tmdb.org/t/p/original/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg', 'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.', 'Fantasy, Action, Comedy', 'Popular'),
(960700, 'Fullmetal Alchemist: The Revenge of Scar', '鋼の錬金術師 完結編 復讐者スカー', '2022-05-20', '/c5OwwBNyJkwyroIOIJL9IiRjydR.jpg', 'https://image.tmdb.org/t/p/original/c5OwwBNyJkwyroIOIJL9IiRjydR.jpg', 'In this sequel to the 2017 live-action netflix Adaptation of the manga the Elric brothers meet their toughest opponent yet — a lone serial killer with a large scar on his forehead.', 'Fantasy, Action, Adventure', 'Popular'),
(756999, 'The Black Phone', 'The Black Phone', '2022-06-22', '/lr11mCT85T1JanlgjMuhs9nMht4.jpg', 'https://image.tmdb.org/t/p/original/lr11mCT85T1JanlgjMuhs9nMht4.jpg', 'Finney Blake, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.', 'Horror, Thriller', 'Now Playing,Popular'),
(766507, 'Prey', 'Prey', '2022-08-02', '/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg', 'https://image.tmdb.org/t/p/original/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg', 'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.', 'Thriller, Action, Science Fiction', 'Popular'),
(758330, 'Good Luck to You, Leo Grande', 'Good Luck to You, Leo Grande', '2022-06-17', '/5wQydIQYho2wz1suPOoPoNgMzCm.jpg', 'https://image.tmdb.org/t/p/original/5wQydIQYho2wz1suPOoPoNgMzCm.jpg', 'Nancy Stokes doesn’t know good sex. Whatever it may be, Nancy, a retired schoolteacher, is pretty sure she has never had it, but she is determined to finally do something about that. She even has a plan: It involves an anonymous hotel room, and a young sex worker who calls himself Leo Grande.', 'Drama, Comedy', 'Now Playing,Upcoming'),
(843633, 'White Elephant', 'White Elephant', '2022-06-03', '/4U32ULTfEz2c456ukx5HCPDVQQ7.jpg', 'https://image.tmdb.org/t/p/original/4U32ULTfEz2c456ukx5HCPDVQQ7.jpg', 'An ex-marine enforcer must battle his conscience and code of honor when he is forced to do things for the mob.', 'Action, Crime, Thriller', 'Popular'),
(810693, 'Jujutsu Kaisen 0', '劇場版 呪術廻戦 0', '2021-12-24', '/yzkgx79vj1KsZBzxFBIsQBwBkPE.jpg', 'https://image.tmdb.org/t/p/original/yzkgx79vj1KsZBzxFBIsQBwBkPE.jpg', 'Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won\'t leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?', 'Animation, Action, Fantasy', 'Popular'),
(781099, 'Inexorable', 'Inexorable', '2022-04-06', '/iiclsw6zgRJz5D5Cc6sn4Cs9GQo.jpg', 'https://image.tmdb.org/t/p/original/iiclsw6zgRJz5D5Cc6sn4Cs9GQo.jpg', 'Desperately seeking inspiration for the follow-up novel to his bestseller \"Inexorable\", Marcel Bellmer moves in his wife\'s old family mansion with his family.', 'Thriller', 'Popular'),
(773867, 'Seoul Vibe', '서울대작전', '2022-08-26', '/ffX0TL3uKerLXACkuZGWhAPMbAq.jpg', 'https://image.tmdb.org/t/p/original/ffX0TL3uKerLXACkuZGWhAPMbAq.jpg', 'Chasing speed, dreams and money, a team of drivers get involved in the slush fund investigation of a powerful figure during the 1988 Seoul Olympics.', 'Action, Crime, Comedy, Adventure', 'Popular'),
(507086, 'Jurassic World Dominion', 'Jurassic World Dominion', '2022-06-01', '/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg', 'https://image.tmdb.org/t/p/original/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg', 'Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.', 'Adventure, Action, Science Fiction', 'Popular'),
(760161, 'Orphan: First Kill', 'Orphan: First Kill', '2022-07-27', '/wSqAXL1EHVJ3MOnJzMhUngc8gFs.jpg', 'https://image.tmdb.org/t/p/original/wSqAXL1EHVJ3MOnJzMhUngc8gFs.jpg', 'After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.', 'Horror, Thriller', 'Now Playing,Popular,Upcoming'),
(772450, 'Presences', 'Presencias', '2022-09-07', '/dgDT3uol3mdvwEg0jt1ble3l9hw.jpg', 'https://image.tmdb.org/t/p/original/dgDT3uol3mdvwEg0jt1ble3l9hw.jpg', 'A man who loses his wife and goes to seclude himself in a cabin in the woods, where strange things happen.', 'Horror', 'Popular'),
(361743, 'Top Gun: Maverick', 'Top Gun: Maverick', '2022-05-24', '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg', 'https://image.tmdb.org/t/p/original/62HCnUTziyWcpDaBO2i1DX17ljH.jpg', 'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.', 'Action, Drama', 'Popular'),
(773975, 'End of the Road', 'End of the Road', '2022-09-09', '/tLFIMuPWJHlTJ6TN8HCOiSD6SdA.jpg', 'https://image.tmdb.org/t/p/original/tLFIMuPWJHlTJ6TN8HCOiSD6SdA.jpg', 'Recently widowed mom Brenda fights to protect her family during a harrowing road trip when a murder and a missing bag of cash plunge them into danger.', 'Thriller, Drama, Crime', 'Popular'),
(838197, 'Watch Out, We\'re Mad', 'Altrimenti ci arrabbiamo', '2022-03-23', '/qlrRi05x5hjoM29hz6TDLGTUSop.jpg', 'https://image.tmdb.org/t/p/original/qlrRi05x5hjoM29hz6TDLGTUSop.jpg', 'Carezza and Sorriso, brothers very different from each other and in quarrel since childhood, will have to put aside their controversies to recover the legendary Dune Buggy, once belonged to their beloved father and now stolen from him by Torsillo, an unscrupulous building speculator, and his son Raniero. In doing so, they will forge an unusual alliance with a circus community, headed by the beautiful and dangerous Miriam and threatened by Torsillo\'s dirty business. Between daring chases, memorable fights and delicate meals based on beer and sausages, will the two brothers be able to find their beloved car?', 'Comedy, Action', 'Popular'),
(952374, 'The Aviary', 'The Aviary', '2022-04-29', '/u6HUQcOQsgkFFO8xCITfxQz6ivc.jpg', 'https://image.tmdb.org/t/p/original/u6HUQcOQsgkFFO8xCITfxQz6ivc.jpg', 'A twisted journey of two women’s desperate flee to escape the clutches of Skylight, an insidious cult. Lured in by the promise of “freedom” in the isolated desert campus called The Aviary, Jillian and Blair join forces to escape in hopes of real freedom. Consumed by fear and paranoia, they can’t shake the feeling that they are being followed by the cult’s leader, Seth, a man as seductive as he is controlling. The more distance the pair gains from the cult, the more Seth holds control of their minds. With supplies dwindling and their senses failing, Jillian and Blair are faced with a horrifying question: how do you run from an enemy who lives inside your head?', 'Thriller', 'Popular'),
(1015602, 'Welcome to the Club', 'Welcome to the Club', '2022-09-08', '/kxB9E6fo0ycHzd13oOTHmGa5Njd.jpg', 'https://image.tmdb.org/t/p/original/kxB9E6fo0ycHzd13oOTHmGa5Njd.jpg', 'Heart set on becoming a princess, Lisa Simpson is surprised to learn being bad might be more fun.', 'Animation, Comedy', 'Popular'),
(927341, 'Hunting Ava Bravo', 'Hunting Ava Bravo', '2022-04-01', '/etc6HKBEhNySNnYU2nRgbSeIyoW.jpg', 'https://image.tmdb.org/t/p/original/etc6HKBEhNySNnYU2nRgbSeIyoW.jpg', 'Billionaire sportsman Buddy King unwinds by hunting human captives on his remote mountain estate. But his latest victim, Ava Bravo is no easy target.', 'Horror, Thriller, Action, Adventure, Crime, Mystery, Drama, War', 'Popular'),
(760741, 'Beast', 'Beast', '2022-08-11', '/iRV0IB5xQeOymuGGUBarTecQVAl.jpg', 'https://image.tmdb.org/t/p/original/iRV0IB5xQeOymuGGUBarTecQVAl.jpg', 'A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.', 'Adventure, Drama, Horror', 'Now Playing,Popular'),
(76600, 'Avatar: The Way of Water', 'Avatar: The Way of Water', '2022-12-14', '/1yppMeTNQwDrzaUH4dRCx4mr8We.jpg', 'https://image.tmdb.org/t/p/original/1yppMeTNQwDrzaUH4dRCx4mr8We.jpg', 'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.', 'Science Fiction, Action, Adventure', 'Popular'),
(951368, 'Your Boyfriend Is Mine', 'Your Boyfriend Is Mine', '2022-03-19', '/2OOYNZLKjdX8Z5KNyz7zZnHmodJ.jpg', 'https://image.tmdb.org/t/p/original/2OOYNZLKjdX8Z5KNyz7zZnHmodJ.jpg', 'Over the objection of his girlfriend, Ben agrees to take a job as the “live in” man servant to a wealthy businesswoman, Amanda, but quickly realizes he has made a deal with the devil, and has put himself and his girlfriend in mortal jeopardy', 'Thriller, TV Movie, Action', 'Popular'),
(453395, 'Doctor Strange in the Multiverse of Madness', 'Doctor Strange in the Multiverse of Madness', '2022-05-04', '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg', 'https://image.tmdb.org/t/p/original/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg', 'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.', 'Fantasy, Action, Adventure', 'Popular'),
(997120, 'Sniper: Rogue Mission', 'Sniper: Rogue Mission', '2022-08-15', '/jSL5TqroJsDAIgBdELBwby1uhf1.jpg', 'https://image.tmdb.org/t/p/original/jSL5TqroJsDAIgBdELBwby1uhf1.jpg', 'When a crooked federal agent is involved in a human sex trafficking ring, Sniper and CIA Rookie Brandon Beckett goes rogue, teaming up with his former allies Homeland Security Agent Zero and assassin Lady Death to uncover the corrupt agent and take down the criminal organization.', 'Action, Thriller, Mystery', 'Popular'),
(762504, 'Nope', 'Nope', '2022-07-20', '/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg', 'https://image.tmdb.org/t/p/original/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg', 'Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.', 'Horror, Mystery, Science Fiction, Thriller', 'Now Playing,Popular'),
(585511, 'Luck', 'Luck', '2022-08-05', '/1HOYvwGFioUFL58UVvDRG6beEDm.jpg', 'https://image.tmdb.org/t/p/original/1HOYvwGFioUFL58UVvDRG6beEDm.jpg', 'Suddenly finding herself in the never-before-seen Land of Luck, the unluckiest person in the world must unite with the magical creatures there to turn her luck around.', 'Animation, Adventure, Comedy, Fantasy', 'Popular'),
(936897, 'Curious Caterer: Dying for Chocolate', 'Curious Caterer: Dying for Chocolate', '2022-04-10', '/7quPRcCVUmMBxKO58QwPuIADtYG.jpg', 'https://image.tmdb.org/t/p/original/7quPRcCVUmMBxKO58QwPuIADtYG.jpg', 'Goldy is a spirited single mom who’s thrust into the role of town sleuth to help solve a friend’s mysterious death. With the clock ticking to find the culprit, Goldy strikes up an unlikely partnership with Detective Tom Schultz, who leans into Goldy’s local knowledge. As their relationship shows signs of becoming something more, the suspect list rises. Will Goldy narrow in on the killer before the killer narrows in on her?', 'TV Movie, Mystery', 'Popular'),
(924482, 'The Ledge', 'The Ledge', '2022-02-18', '/dHKfsdNcEPw7YIWFPIhqiuWrSAb.jpg', 'https://image.tmdb.org/t/p/original/dHKfsdNcEPw7YIWFPIhqiuWrSAb.jpg', 'A rock climbing adventure between two friends turns into a terrifying nightmare. After Kelly captures the murder of her best friend on camera, she becomes the next target of a tight knit group of friends who will stop at nothing to destroy the evidence and anyone in their way. Desperate for her safety, she begins a treacherous climb up a mountain cliff and her survival instincts are put to the test when she becomes trapped with the killers just 20 feet away.', 'Thriller, Adventure, Mystery, Action, Crime', 'Popular'),
(848123, 'Black Site', 'Black Site', '2022-05-05', '/ipn8khVVC4eToWiGf89WF9J5PJn.jpg', 'https://image.tmdb.org/t/p/original/ipn8khVVC4eToWiGf89WF9J5PJn.jpg', 'A group of officers based in a labyrinthine top-secret prison must fight for their lives against Hatchet, a brilliant and infamous high-value detainee. When he escapes, his mysterious and deadly agenda has far reaching and dire consequences.', 'Action, Thriller', 'Popular'),
(238, 'The Godfather', 'The Godfather', '1972-03-14', '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'Drama, Crime', 'Top Rated'),
(278, 'The Shawshank Redemption', 'The Shawshank Redemption', '1994-09-23', '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'Drama, Crime', 'Top Rated'),
(240, 'The Godfather Part II', 'The Godfather Part II', '1974-12-20', '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', 'https://image.tmdb.org/t/p/original/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'Drama, Crime', 'Top Rated'),
(19404, 'Dilwale Dulhania Le Jayenge', 'दिलवाले दुल्हनिया ले जायेंगे', '1995-10-19', '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg', 'https://image.tmdb.org/t/p/original/2CAL2433ZeIihfX1Hb2139CX0pW.jpg', 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'Comedy, Drama, Romance', 'Top Rated'),
(424, 'Schindler\'s List', 'Schindler\'s List', '1993-12-15', '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 'https://image.tmdb.org/t/p/original/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'Drama, History, War', 'Top Rated'),
(667257, 'Impossible Things', 'Cosas imposibles', '2021-06-17', '/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg', 'https://image.tmdb.org/t/p/original/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg', 'Matilde is a woman who, after the death of her husband - a man who constantly abused her - finds her new best friend in Miguel, her young, insecure, disoriented and even dealer neighbor', 'Family, Drama', 'Top Rated'),
(129, 'Spirited Away', '千と千尋の神隠し', '2001-07-20', '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 'Animation, Family, Fantasy', 'Top Rated'),
(372058, 'Your Name.', '君の名は。', '2016-08-26', '/q719jXXEzOoYaps6babgKnONONX.jpg', 'https://image.tmdb.org/t/p/original/q719jXXEzOoYaps6babgKnONONX.jpg', 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', 'Romance, Animation, Drama', 'Top Rated'),
(389, '12 Angry Men', '12 Angry Men', '1957-04-10', '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg', 'https://image.tmdb.org/t/p/original/ppd84D2i9W8jXmsyInGyihiSyqz.jpg', 'The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors\' prejudices and preconceptions about the trial, the accused, and each other.', 'Drama', 'Top Rated'),
(496243, 'Parasite', '기생충', '2019-05-30', '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.', 'Comedy, Thriller, Drama', 'Top Rated'),
(724089, 'Gabriel\'s Inferno: Part II', 'Gabriel\'s Inferno: Part II', '2020-07-31', '/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg', 'https://image.tmdb.org/t/p/original/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg', 'Professor Gabriel Emerson finally learns the truth about Julia Mitchell\'s identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another\'s arms?', 'Romance', 'Top Rated'),
(696374, 'Gabriel\'s Inferno', 'Gabriel\'s Inferno', '2020-05-29', '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg', 'https://image.tmdb.org/t/p/original/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg', 'An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel\'s Inferno is a captivating and wildly passionate tale of one man\'s escape from his own personal hell as he tries to earn the impossible--forgiveness and love.', 'Romance', 'Top Rated'),
(372754, 'Dou kyu sei – Classmates', '同級生', '2016-02-20', '/cIfRCA5wEvj9tApca4UDUagQEiM.jpg', 'https://image.tmdb.org/t/p/original/cIfRCA5wEvj9tApca4UDUagQEiM.jpg', 'Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.', 'Romance, Animation', 'Top Rated'),
(497, 'The Green Mile', 'The Green Mile', '1999-12-10', '/velWPhVMQeQKcxggNEU8YmIo52R.jpg', 'https://image.tmdb.org/t/p/original/velWPhVMQeQKcxggNEU8YmIo52R.jpg', 'A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people\'s ailments. When the cell block\'s head guard, Paul Edgecomb, recognizes Coffey\'s miraculous gift, he tries desperately to help stave off the condemned man\'s execution.', 'Fantasy, Drama, Crime', 'Top Rated'),
(155, 'The Dark Knight', 'The Dark Knight', '2008-07-14', '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'Drama, Action, Crime, Thriller', 'Top Rated'),
(730154, 'Your Eyes Tell', 'きみの瞳が問いかけている', '2020-10-23', '/cVn8E3Fxbi8HzYYtaSfsblYC4gl.jpg', 'https://image.tmdb.org/t/p/original/cVn8E3Fxbi8HzYYtaSfsblYC4gl.jpg', 'A tragic accident lead to Kaori\'s blindness, but she clings to life and the smaller pleasures it can still afford her. She meets Rui and begins to talk to him. Rui was once a promising kickboxer, but something happened in his past. Kaori\'s smile brings out a change in Rui. However, the two are connected in more than one way. Rui attempts to do what is right.', 'Romance, Drama', 'Top Rated'),
(553512, 'Burn the Stage: The Movie', '번 더 스테이지: 더 무비', '2018-11-15', '/pJKy1yvnKh8UjcuYeG3Rt35xHFA.jpg', 'https://image.tmdb.org/t/p/original/pJKy1yvnKh8UjcuYeG3Rt35xHFA.jpg', 'A documentary following the worldwide famous music group BTS, as they tour the world and share their experience along with their beloved band friends and fans.', 'Music', 'Top Rated'),
(680, 'Pulp Fiction', 'Pulp Fiction', '1994-09-10', '/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg', 'https://image.tmdb.org/t/p/original/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg', 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.', 'Thriller, Crime', 'Top Rated'),
(429, 'The Good, the Bad and the Ugly', 'Il buono, il brutto, il cattivo', '1966-12-23', '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', 'https://image.tmdb.org/t/p/original/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', 'Western', 'Top Rated'),
(122, 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Return of the King', '2003-12-01', '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'https://image.tmdb.org/t/p/original/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron\'s forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord\'s realm.', 'Adventure, Fantasy, Action', 'Top Rated'),
(13, 'Forrest Gump', 'Forrest Gump', '1994-06-23', '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg', 'https://image.tmdb.org/t/p/original/saHP97rTPS5eLmrLQEcANmKrsFl.jpg', 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 'Comedy, Drama, Romance', 'Top Rated'),
(761053, 'Gabriel\'s Inferno: Part III', 'Gabriel\'s Inferno: Part III', '2020-11-19', '/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg', 'https://image.tmdb.org/t/p/original/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg', 'The final part of the film adaption of the erotic romance novel Gabriel\'s Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.', 'Romance, Comedy', 'Top Rated'),
(769, 'GoodFellas', 'GoodFellas', '1990-09-12', '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', 'https://image.tmdb.org/t/p/original/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.', 'Drama, Crime', 'Top Rated'),
(11216, 'Cinema Paradiso', 'Nuovo Cinema Paradiso', '1988-11-17', '/9JhfVOveaY00o8njQu2Xrp4YWud.jpg', 'https://image.tmdb.org/t/p/original/9JhfVOveaY00o8njQu2Xrp4YWud.jpg', 'A filmmaker recalls his childhood, when he fell in love with the movies at his village\'s theater and formed a deep friendship with the theater\'s projectionist.', 'Drama, Romance', 'Top Rated'),
(346, 'Seven Samurai', '七人の侍', '1954-04-26', '/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg', 'https://image.tmdb.org/t/p/original/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg', 'A samurai answers a village\'s request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.', 'Action, Drama', 'Top Rated'),
(637, 'Life Is Beautiful', 'La vita è bella', '1997-12-20', '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg', 'https://image.tmdb.org/t/p/original/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg', 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.', 'Comedy, Drama', 'Top Rated'),
(14537, 'Harakiri', '切腹', '1962-09-15', '/w7pWcLaYQkbtRUn99K6ome0DblL.jpg', 'https://image.tmdb.org/t/p/original/w7pWcLaYQkbtRUn99K6ome0DblL.jpg', 'Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.', 'Action, Drama, History', 'Top Rated'),
(311, 'Once Upon a Time in America', 'Once Upon a Time in America', '1984-05-23', '/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg', 'https://image.tmdb.org/t/p/original/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg', 'A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.', 'Drama, Crime', 'Top Rated'),
(12477, 'Grave of the Fireflies', '火垂るの墓', '1988-04-16', '/qG3RYlIVpTYclR9TYIsy8p7m7AT.jpg', 'https://image.tmdb.org/t/p/original/qG3RYlIVpTYclR9TYIsy8p7m7AT.jpg', 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.', 'Animation, Drama, War', 'Top Rated'),
(539, 'Psycho', 'Psycho', '1960-06-22', '/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg', 'https://image.tmdb.org/t/p/original/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg', 'When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.', 'Horror, Drama, Thriller', 'Top Rated'),
(40096, 'A Dog\'s Will', 'O Auto da Compadecida', '2000-09-15', '/m8eFedsS7vQCZCS8WGp5n1bVD0q.jpg', 'https://image.tmdb.org/t/p/original/m8eFedsS7vQCZCS8WGp5n1bVD0q.jpg', 'The lively Jack the Cricket and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.', 'Comedy, Drama, Fantasy', 'Top Rated'),
(550, 'Fight Club', 'Fight Club', '1999-10-15', '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', 'https://image.tmdb.org/t/p/original/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.', 'Drama', 'Top Rated'),
(510, 'One Flew Over the Cuckoo\'s Nest', 'One Flew Over the Cuckoo\'s Nest', '1975-11-19', '/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg', 'https://image.tmdb.org/t/p/original/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg', 'A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.', 'Drama', 'Top Rated'),
(652837, 'Josee, the Tiger and the Fish', 'ジョゼと虎と魚たち', '2020-12-25', '/z1D8xi9x4uEhyFruo7uEHXUMD4K.jpg', 'https://image.tmdb.org/t/p/original/z1D8xi9x4uEhyFruo7uEHXUMD4K.jpg', 'With dreams of diving abroad, Tsuneo gets a job assisting Josee, an artist whose imagination takes her far beyond her wheelchair. But when the tide turns against them, they push each other to places they never thought possible, and inspire a love fit for a storybook.', 'Animation, Drama, Romance', 'Top Rated'),
(704264, 'Primal: Tales of Savagery', 'Primal: Tales of Savagery', '2019-11-21', '/9NBBkdxH0TjQEBSN2AzeE1sgsF9.jpg', 'https://image.tmdb.org/t/p/original/9NBBkdxH0TjQEBSN2AzeE1sgsF9.jpg', 'Genndy Tartakovsky\'s Primal: Tales of Savagery features a caveman and a dinosaur on the brink of extinction. Bonded by tragedy, this unlikely friendship becomes the only hope of survival.', 'Action, Adventure, Animation, Drama', 'Top Rated'),
(255709, 'Hope', '소원', '2013-10-02', '/1xXaGHQYZGh1RBjP8yTl7vjW6qZ.jpg', 'https://image.tmdb.org/t/p/original/1xXaGHQYZGh1RBjP8yTl7vjW6qZ.jpg', 'After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.', 'Drama, Family', 'Top Rated'),
(598, 'City of God', 'Cidade de Deus', '2002-02-05', '/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg', 'https://image.tmdb.org/t/p/original/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg', 'In the slums of Rio, two kids\' paths diverge as one struggles to become a photographer and the other a kingpin.', 'Drama, Crime', 'Top Rated'),
(324857, 'Spider-Man: Into the Spider-Verse', 'Spider-Man: Into the Spider-Verse', '2018-12-06', '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', 'https://image.tmdb.org/t/p/original/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', 'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson \"Kingpin\" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.', 'Action, Adventure, Animation, Science Fiction', 'Top Rated'),
(92321, 'Hotarubi no Mori e', '蛍火の杜へ', '2011-09-17', '/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg', 'https://image.tmdb.org/t/p/original/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg', 'One hot summer day a little girl gets lost in an enchanted forest of the mountain god where spirits reside. A young boy appears before her, but she cannot touch him for fear of making him disappear. And so a wondrous adventure awaits...', 'Romance, Animation, Fantasy', 'Top Rated'),
(378064, 'A Silent Voice: The Movie', '映画 聲の形', '2016-09-17', '/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg', 'https://image.tmdb.org/t/p/original/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg', 'Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?', 'Animation, Drama', 'Top Rated'),
(900667, 'One Piece Film Red', 'ONE PIECE FILM RED', '2022-08-06', '/m80kPdrmmtEh9wlLroCp0bwUGH0.jpg', 'https://image.tmdb.org/t/p/original/m80kPdrmmtEh9wlLroCp0bwUGH0.jpg', 'Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as “otherworldly.” She will appear in public for the first time at a live concert. As the venue fills with all kinds of Uta fans — excited pirates, the Navy watching closely, and the Straw Hats led by Luffy who simply came to enjoy her sonorous performance — the voice that the whole world has been waiting for is about to resound.', 'Animation, Adventure, Action, Fantasy', 'Now Playing,Upcoming');
INSERT INTO `movie` (`id`, `movie_name`, `original_name`, `release_date`, `image`, `image_link`, `overview`, `genres`, `category`) VALUES
(921360, 'Wire Room', 'Wire Room', '2022-09-02', '/b9ykj4v8ykjRoGB7SpI1OuxblNU.jpg', 'https://image.tmdb.org/t/p/original/b9ykj4v8ykjRoGB7SpI1OuxblNU.jpg', 'New recruit Justin Rosa must monitor arms-smuggling cartel member Eddie Flynn — and keep him alive at all costs. When a SWAT team descends on Flynn’s home, Rosa breaks protocol and contacts the gangster directly to save his life. As gunmen break into the Wire Room and chaos erupts, Mueller and Rosa make a final, desperate stand against the corrupt agents and officials who seek to destroy evidence and kill them both.', 'Action, Crime, Thriller', 'Now Playing,Popular'),
(948333, 'Into the Deep', 'Into the Deep', '2022-08-26', '/bPyBqGBYjGzyLVHJEIsCwlZejk.jpg', 'https://image.tmdb.org/t/p/original/bPyBqGBYjGzyLVHJEIsCwlZejk.jpg', 'Follows a woman desperate to escape her town, she meets a stranger who promises a romantic escape, but it results in deceit, mistrust, and violence.', 'Thriller', 'Now Playing,Upcoming'),
(629542, 'The Bad Guys', 'The Bad Guys', '2022-03-17', '/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg', 'https://image.tmdb.org/t/p/original/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg', 'When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.', 'Animation, Comedy, Family, Crime', 'Upcoming'),
(436270, 'Black Adam', 'Black Adam', '2022-10-19', '/3zXceNTtyj5FLjwQXuPvLYK5YYL.jpg', 'https://image.tmdb.org/t/p/original/3zXceNTtyj5FLjwQXuPvLYK5YYL.jpg', 'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods and imprisoned just as quickly Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.', 'Action, Fantasy, Adventure', 'Upcoming'),
(985939, 'Fall', 'Fall', '2022-08-11', '/spCAxD99U1A6jsiePFoqdEcY0dG.jpg', 'https://image.tmdb.org/t/p/original/spCAxD99U1A6jsiePFoqdEcY0dG.jpg', 'For best friends Becky and Hunter, life is all about conquering fears and pushing limits. But after they climb 2,000 feet to the top of a remote, abandoned radio tower, they find themselves stranded with no way down. Now Becky and Hunter’s expert climbing skills will be put to the ultimate test as they desperately fight to survive the elements, a lack of supplies, and vertigo-inducing heights', 'Thriller', 'Now Playing,Popular'),
(834742, 'First Love', 'First Love', '2022-06-17', '/gwLNm5VYq68Q65100uOr5fyAh9A.jpg', 'https://image.tmdb.org/t/p/original/gwLNm5VYq68Q65100uOr5fyAh9A.jpg', 'A young man’s difficult entry into adulthood, who experiences the highs and lows of his first love, while dealing with the familial fallout spurred by the financial crisis of 2008.', 'Romance, Drama', 'Upcoming'),
(882598, 'Smile', 'Smile', '2022-09-23', '/hiaeZKzwsk4y4atFhmncO5KRxeT.jpg', 'https://image.tmdb.org/t/p/original/hiaeZKzwsk4y4atFhmncO5KRxeT.jpg', 'After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can\'t explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.', 'Horror, Mystery', 'Upcoming'),
(913290, 'Barbarian', 'Barbarian', '2022-09-08', '/d0Lhdp9AX70vdvVfhnSraaWw06R.jpg', 'https://image.tmdb.org/t/p/original/d0Lhdp9AX70vdvVfhnSraaWw06R.jpg', 'In town for a job interview, a young woman arrives at her Airbnb late at night only to find that it has been mistakenly double-booked and a strange man is already staying there. Against her better judgement, she decides to stay the night anyway, but soon discovers that there is much more to be afraid of in the house than the other guest.', 'Horror, Mystery, Thriller', 'Upcoming'),
(676701, 'Tad the Lost Explorer and the Curse of the Mummy', 'Tadeo Jones 3: La Tabla Esmeralda', '2022-08-24', '/yt0CGOtKbFGR4bqLnDyB0rJeUrZ.jpg', 'https://image.tmdb.org/t/p/original/yt0CGOtKbFGR4bqLnDyB0rJeUrZ.jpg', 'Tad would love for his archeologist colleagues to accept him as one of their own, but he always messes everything up. Tad accidentally destroys a sarcophagus and unleashes an ancient spell endangering the lives of his friends: Mummy, Jeff and Belzoni. With everyone against him and only helped by Sara, he sets off on an adventure that will take him from Mexico to Chicago and from Paris to Egypt, in order to put an end to the curse of the Mummy.', 'Adventure, Animation, Comedy, Family, Fantasy', 'Upcoming'),
(616820, 'Halloween Ends', 'Halloween Ends', '2022-10-12', '/3aEJDJ9O8lsRMM9Xaxxm5kNyt0N.jpg', 'https://image.tmdb.org/t/p/original/3aEJDJ9O8lsRMM9Xaxxm5kNyt0N.jpg', 'Four years after the events of Halloween in 2018, Laurie has decided to liberate herself from fear and rage and embrace life. But when a young man is accused of killing a boy he was babysitting, it ignites a cascade of violence and terror that will force Laurie to finally confront the evil she can’t control, once and for all.', 'Horror, Mystery, Thriller', 'Upcoming'),
(556694, 'Three Thousand Years of Longing', 'Three Thousand Years of Longing', '2022-08-24', '/8q6BrcwGEBGbtwtbCUVKEt2lmEy.jpg', 'https://image.tmdb.org/t/p/original/8q6BrcwGEBGbtwtbCUVKEt2lmEy.jpg', 'A solitary scholar discovers an ancient bottle while on a trip to Istanbul and unleashes a djinn who offers her three wishes. Filled with reluctance, she is unable to come up with one until his stories spark in her a desire to be loved.', 'Fantasy, Drama, Romance', 'Upcoming'),
(724495, 'The Woman King', 'The Woman King', '2022-09-15', '/438QXt1E3WJWb3PqNniK0tAE5c1.jpg', 'https://image.tmdb.org/t/p/original/438QXt1E3WJWb3PqNniK0tAE5c1.jpg', 'The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.', 'Action, Drama, History', 'Upcoming'),
(754609, 'Mrs. Harris Goes to Paris', 'Mrs. Harris Goes to Paris', '2022-07-15', '/eUg0HDLhTEDcXGBU2iK6QRBILv4.jpg', 'https://image.tmdb.org/t/p/original/eUg0HDLhTEDcXGBU2iK6QRBILv4.jpg', 'A 1950s London cleaning lady falls in love with an haute couture dress by Christian Dior and decides to gamble everything for the sake of this folly.', 'Comedy, Drama', 'Upcoming'),
(545611, 'Everything Everywhere All at Once', 'Everything Everywhere All at Once', '2022-03-24', '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg', 'https://image.tmdb.org/t/p/original/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg', 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what\'s important to her by connecting with the lives she could have led in other universes.', 'Action, Adventure, Science Fiction', 'Upcoming'),
(746333, 'Superwho?', 'Super-héros malgré lui', '2022-02-02', '/Aie2kiYOUgZeakpshM2N64PKof1.jpg', 'https://image.tmdb.org/t/p/original/Aie2kiYOUgZeakpshM2N64PKof1.jpg', 'Struggling actor Cedric seems doomed to lead the life of a loser. He\'s broke and his girlfriend has dumped him. Even his own father, sister and best buddies have lost faith in his ability to do anything worthwhile. Then finally, he gets a lead role: the superhero “Badman“. A chance to pull himself out of an endless downward spiral and gain his father\'s respect. But fate strikes again! Rushing off the set in full costume, Cedric has a car accident, loses his memory, and wakes up convinced he really is a superhero on mission! Confronted with real-life adventure and danger, his true nature is put to the test. Does he have what it takes to tackle the forces of evil, defend the weakest among us and beat the bad guys? But you can\'t just decide to be a hero, let alone a superhero... especially someone like Cedric!', 'Comedy, Action', 'Upcoming'),
(520023, 'Bodies Bodies Bodies', 'Bodies Bodies Bodies', '2022-08-05', '/uU3YoLSaVBOaMryzhuiiRWDFbIw.jpg', 'https://image.tmdb.org/t/p/original/uU3YoLSaVBOaMryzhuiiRWDFbIw.jpg', 'In an isolated family mansion, a group of rich 20-somethings decides to play Bodies Bodies Bodies, a game where one of them is secretly a \"killer\" while the rest tries to \"escape\". Things take a turn for the worse when real bodies start turning up, setting off a paranoid and dangerous chain of events.', 'Comedy, Horror, Mystery', 'Upcoming'),
(664469, 'Amsterdam', 'Amsterdam', '2022-09-27', '/chCrPG0LJeilfJwsWPAfmWiJI2T.jpg', 'https://image.tmdb.org/t/p/original/chCrPG0LJeilfJwsWPAfmWiJI2T.jpg', 'In the 1930s, three friends—a doctor, a nurse, and an attorney—witness a murder, become suspects themselves and uncover one of the most outrageous plots in North American history.', 'Drama, History, Crime', 'Upcoming'),
(588921, 'AINBO: Spirit of the Amazon', 'AINBO: Spirit of the Amazon', '2021-02-09', '/oggYIix1tF2SVhg17wv5WLcqCs5.jpg', 'https://image.tmdb.org/t/p/original/oggYIix1tF2SVhg17wv5WLcqCs5.jpg', 'An epic journey of a young hero and her Spirit Guides, \'Dillo\' a cute and humorous armadillo and \"Vaca\" a goofy oversized tapir, who embark on a quest to save their home in the spectacular Amazon Rainforest.', 'Adventure, Animation, Family, Fantasy', 'Upcoming'),
(842942, 'Bandit', 'Bandit', '2022-09-23', '/yph9PAbmjYPvyvbeZvdYIhCZHEu.jpg', 'https://image.tmdb.org/t/p/original/yph9PAbmjYPvyvbeZvdYIhCZHEu.jpg', 'After escaping a Michigan prison, a charming career criminal assumes a new identity in Canada and goes on to rob a record 59 banks and jewellery stores while being hunted by a rogue task force. Based on the story of The Flying Bandit.', 'Crime, Drama, History', 'Upcoming'),
(800939, 'Ticket to Paradise', 'Ticket to Paradise', '2022-09-08', '/9KvarmnOyYvrbeZpplvtcRb4Xlu.jpg', 'https://image.tmdb.org/t/p/original/9KvarmnOyYvrbeZpplvtcRb4Xlu.jpg', 'A divorced couple teams up and travels to Bali to stop their daughter from making the same mistake they think they made 25 years ago.', 'Comedy, Romance', 'Upcoming'),
(676547, 'Prey for the Devil', 'Prey for the Devil', '2022-10-26', '/jXwYESgxqkXlYvoTyUTO2hqKK7T.jpg', 'https://image.tmdb.org/t/p/original/jXwYESgxqkXlYvoTyUTO2hqKK7T.jpg', 'In response to a global rise in demonic possessions, the Catholic Church reopens exorcism schools to train priests in the Rite of Exorcism. On this spiritual battlefield, an unlikely warrior rises: a young nun, Sister Ann. Thrust onto the spiritual frontline with fellow student Father Dante, Sister Ann finds herself in a battle for the soul of a young girl and soon realizes the Devil has her right where he wants her.', 'Horror, Thriller', 'Upcoming'),
(283566, 'Evangelion: 3.0+1.0 Thrice Upon a Time', 'シン・エヴァンゲリオン劇場版:||', '2021-03-08', '/md5wZRRj8biHrGtyitgBZo7674t.jpg', 'https://image.tmdb.org/t/p/original/md5wZRRj8biHrGtyitgBZo7674t.jpg', 'In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.', 'Animation, Action, Science Fiction, Drama', 'Upcoming'),
(614939, 'Bros', 'Bros', '2022-09-30', '/4CArWLRroMPXwKJeO3HSYiyKyHD.jpg', 'https://image.tmdb.org/t/p/original/4CArWLRroMPXwKJeO3HSYiyKyHD.jpg', 'Two men with commitment problems attempt a relationship.', 'Comedy, Romance', 'Upcoming'),
(799379, 'Project Wolf Hunting', '늑대사냥', '2022-09-28', '/h1pLOZATBr7oVDrwj3DfOjTOCGk.jpg', 'https://image.tmdb.org/t/p/original/h1pLOZATBr7oVDrwj3DfOjTOCGk.jpg', 'During transport from the Philippines to South Korea, a group of dangerous criminals unites to stage a coordinated escape attempt. As the jailbreak escalates into a bloody, all-out riot, the fugitives and their allies from the outside exact a brutal terror campaign against the special agents onboard the ship.', 'Science Fiction, Action, Thriller', 'Upcoming'),
(553600, 'Promare', 'プロメア', '2019-05-24', '/4fVcLdImgW2EXQyrflA5oLTvwCD.jpg', 'https://image.tmdb.org/t/p/original/4fVcLdImgW2EXQyrflA5oLTvwCD.jpg', 'Galo and the Burning Rescue Fire Department face off against BURNISH, a group of mutants who are able to control and wield flames, and the fire disaster they have unleashed on Earth.', 'Animation, Action, Science Fiction', 'Upcoming'),
(366672, 'Paws of Fury: The Legend of Hank', 'Paws of Fury: The Legend of Hank', '2022-07-14', '/vccE9bBa9mgghFpkWzU1fQqmOKB.jpg', 'https://image.tmdb.org/t/p/original/vccE9bBa9mgghFpkWzU1fQqmOKB.jpg', 'A hard-on-his-luck hound finds himself in a town full of cats in need of a hero to defend them from a ruthless villain\'s wicked plot to wipe their village off the map. With help from a reluctant mentor, our underdog must assume the role of town samurai and team up with the villagers to save the day.', 'Family, Comedy, Animation, Action', 'Upcoming'),
(830784, 'Lyle, Lyle, Crocodile', 'Lyle, Lyle, Crocodile', '2022-10-07', '/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg', 'https://image.tmdb.org/t/p/original/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg', 'When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle - a singing crocodile who loves baths, caviar and great music-living in the attic of his new home. The two become fast friends, but when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primm’s must band together with Lyle’s charismatic owner, Hector P. Valenti, to show the world that family can come from the most unexpected places and there’s nothing wrong with a big singing crocodile with an even bigger personality.', 'Family, Comedy, Music', 'Upcoming'),
(663712, 'Terrifier 2', 'Terrifier 2', '2022-10-06', '/wRKHUqYGrp3PO91mZVQ18xlwYzW.jpg', 'https://image.tmdb.org/t/p/original/wRKHUqYGrp3PO91mZVQ18xlwYzW.jpg', 'After being resurrected by a sinister entity, Art the Clown returns to Miles County where he must hunt down and destroy a teenage girl and her younger brother on Halloween night.  As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art\'s evil intent.', 'Horror, Thriller', 'Upcoming'),
(49046, 'All Quiet on the Western Front', 'Im Westen nichts Neues', '2022-09-29', '/glZfjVEzZCJ7oTHWa3m6KefcoRN.jpg', 'https://image.tmdb.org/t/p/original/glZfjVEzZCJ7oTHWa3m6KefcoRN.jpg', 'Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.', 'Action, Drama, History, War', 'Upcoming'),
(819876, 'Crimes of the Future', 'Crimes of the Future', '2022-05-25', '/nWyoiaHAcPouRKKGgZa32p6Txkb.jpg', 'https://image.tmdb.org/t/p/original/nWyoiaHAcPouRKKGgZa32p6Txkb.jpg', 'Humans adapt to a synthetic environment, with new transformations and mutations. With his partner Caprice, Saul Tenser, celebrity performance artist, publicly showcases the metamorphosis of his organs in avant-garde performances.', 'Drama, Horror, Science Fiction', 'Upcoming'),
(683340, 'Vengeance', 'Vengeance', '2022-07-29', '/n1SlTeEv3dNJB3gF9AHAVElQ6LO.jpg', 'https://image.tmdb.org/t/p/original/n1SlTeEv3dNJB3gF9AHAVElQ6LO.jpg', 'A journalist and podcaster from New York City travels to West Texas in order to report on the death of a girl he was hooking up with.', 'Thriller, Mystery, Comedy', 'Upcoming'),
(804251, 'Alcarràs', 'Alcarràs', '2022-04-29', '/o1GKiyozTFsVAPTtZKJT81gDNqz.jpg', 'https://image.tmdb.org/t/p/original/o1GKiyozTFsVAPTtZKJT81gDNqz.jpg', 'For as long as they can remember, the Solé family has spent every summer picking the peaches in their orchard in Alcarràs, a small village in Catalonia. But this year’s crop may well be their last, as they face eviction. The new plans for the land, which include cutting down the peach trees and installing solar panels, cause a rift in this large, tight-knit family. For the first time, they face an uncertain future and risk losing more than their orchard.', 'Drama, Romance', 'Upcoming'),
(497828, 'Triangle of Sadness', 'Triangle of Sadness', '2022-09-23', '/fgy78BLl0gk8OzTWHZyGrSlIEON.jpg', 'https://image.tmdb.org/t/p/original/fgy78BLl0gk8OzTWHZyGrSlIEON.jpg', 'Models Carl and Yaya are invited for a luxury cruise with a rogues\' gallery of super-rich passengers. At first, all appears Instagrammable, but the cruise ends catastrophically and the group find themselves marooned on a desert island.', 'Comedy, Drama', 'Upcoming'),
(522526, 'Mona Lisa and the Blood Moon', 'Mona Lisa and the Blood Moon', '2022-09-30', '/8wlyOODcyWBbjgiS5MbqCqnhtuO.jpg', 'https://image.tmdb.org/t/p/original/8wlyOODcyWBbjgiS5MbqCqnhtuO.jpg', 'A young woman with psychokinetic powers breaks out of a Louisiana asylum and makes her way to New Orleans, where she falls into the city’s netherworld of misfits and miscreants.', 'Science Fiction, Drama', 'Upcoming');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
